### ISSUE TITLE
[meta] KafkaChannel refactorings

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka#386]
**Problem**

Two implementations of the `KafkaChannel` that do not share a lot of code.

**Exit Criteria**

Desired exit goal: One backing implemetation for the `KafkaChannel` API.

Till today and the "desired exit goal", the team will work on refactorings which addresses the concern of code-sharing. Over time the channel implementations will share more and more (common) code, until we reach a point that there is very little DIFF.

Different issues/PRs will be linked to this "uber"/"meta" ticket, as the work is being progressed.

**Time Estimate (optional):**
weeks - it's more an iteration

**Comment by aliok** [comment]
This is the meeting notes that happened in Eventing Delivery group about this initiative: https://docs.google.com/document/d/1f556J18aaG4NUQFawWAcnMAV6_EL_eLCflTyPWn2Yz0/edit

Subtasks:
- [x] https://github.com/knative-sandbox/eventing-kafka/issues/268: Common util for SaramaConfig
- [x] https://github.com/knative-sandbox/eventing-kafka/issues/298: Use Sarama field of config-kafka in consolidated channel and in source
- [ ] https://github.com/knative-sandbox/eventing-kafka/issues/405: Leverage eventing-kafka field of config-kafka in consolidated channel and in source
