### ISSUE TITLE
Kafka code share - umbrella ticket

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka#404]
**Problem**
We would like to increase code share in Kafka components and also make them consistent.

This is just an umbrella ticket to hold subtasks.

This is the meeting notes that happened in Eventing Delivery group about this initiative: https://docs.google.com/document/d/1f556J18aaG4NUQFawWAcnMAV6_EL_eLCflTyPWn2Yz0/edit

Subtasks:
- [x] https://github.com/knative-sandbox/eventing-kafka/issues/268: Common util for SaramaConfig
- [x] https://github.com/knative-sandbox/eventing-kafka/issues/298: Use Sarama field of config-kafka in consolidated channel and in source
- [ ] https://github.com/knative-sandbox/eventing-kafka/issues/405: Leverage eventing-kafka field of config-kafka in consolidated channel and in source

**Comment by aliok** [comment]
/close

Duplicate of https://github.com/knative-sandbox/eventing-kafka/issues/386
