### ISSUE TITLE
ResetOffset Command

### ISSUE THREAD

**Issue by travis-minke-sap** [knative-sandbox/eventing-kafka#588]
**Problem**
Users of Kafka resources need the ability to reposition the Offsets of a particular ConsumerGroup in order to recover from unexpected downtime. The associated Feature Track [document](https://docs.google.com/document/d/1sbvxEWTB7l6eADk4WyddHLEtH1q9cv7rlSbiBivHGMs/edit?usp=sharing&resourcekey=0-Ngyt3ddYC1ltSP1g59eYXQ) contains a detailed description of the feature. This Issue is the top-level coordination point for the various PRs expected to be required to implement this feature.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
This new feature is targeted at the Cluster Admin and/or Event Subscriber personas.

**Exit Criteria**
Users are provided a mechanism by which they can reposition the Offsets of a particular ConsumerGroup based on a specified timestamp.

**Time Estimate (optional):**
Many... This is a new feature comprising a new CRD, Controller, etc which is being implemented in a re-usable fashion so that multiple Kafka Channel/Broker implementations can make use of it.

**Tasks**
- [X] Create ResetOffset CRD and generate informers / listers / etc. (PR #589)
- [X] Create ResetOffset Controller with initial reconciliation framework. (partial implementation) (PR #626)
- [X] Define stop/start ConsumerGroup Messages (PRs #724, #725)
- [X] Map ResetOffset Ref to dataplane and send control-protocol messags (PR #725)
- [X] Common Consumer Stop/Start ConsumerGroups in response to control-protocol messaging. (PR #724)
- [X] Add Sync/Locking to Consumer Manager & Controller (PR #741 and #742 and #746)
- [X] Add ResetOffset Admission/Validation support to KafkaChannel Webhook (#753)
- [X] Verify / handle Subscription Status while consumergroup stopped. (#755)
- [ ] ~~Deal with duplicate reconciliation race condition (K8S Status update)~~ NO LONGER OCCURRING
- [X] Create ResetOffset Controller common RBAC (#750)
- [X] Add ResetOffset Controller to KafkaChannel Controllers (#761)
- [X] New Documentation on ResetOffset usage in KafkaChannels (#745, and [docs 4012](https://github.com/knative/docs/pull/4012))
- [X] Create e2e tests (#781)

**Comment by ssandanshi** [comment]
I would really like this feature. We have the use case for resetting offsets and had to do it via the kafka cluster directly. This will make that process much simpler. Let me know if I can help in the design and tasks.

**Comment by vayyappaneni** [comment]
We are currently doing in manual way to reset topic offsets to read the data from Kafka to re-processing data and to recover from unexpected downtime.

**Comment by travis-minke-sap** [comment]
Closing this issue as all the sub-tasks are now complete.  The ResetOffset feature will be considered "live" in the next release (v0.25.0).  This is in place for the Distributed KafkaChannel only at this point.  Follow up Issue #788 was created to enable it in the Consolidated KafkaChannel.
