### ISSUE TITLE
Umbrella issue - KafkaSource storage version upgrade

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka#65]
**Problem**
Need to update KafkaSource storage version to v1beta1.

Moved from https://github.com/knative/eventing-contrib/issues/1394

Relevant work is tracked here.

- [ ] Upgrade tests: https://github.com/knative-sandbox/eventing-kafka/issues/67
- [ ] Make v1beta1 the stored version: https://github.com/knative-sandbox/eventing-kafka/issues/68
- [ ] Remove v1alpha1 API shape: https://github.com/knative-sandbox/eventing-kafka/issues/66
