### ISSUE TITLE
Umbrella issue - KafkaChannel storage version upgrade

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka#70]
**Problem**
Need to update KafkaChannel storage version to v1beta1.

Moved from https://github.com/knative/eventing-contrib/issues/1396

Relevant work is tracked here.

- [x] Upgrade tests: https://github.com/knative-sandbox/eventing-kafka/issues/72
- [x] Make v1beta1 the stored version: https://github.com/knative-sandbox/eventing-kafka/issues/73
- [x] Remove v1alpha1 API shape: https://github.com/knative-sandbox/eventing-kafka/issues/71 https://github.com/knative-sandbox/eventing-kafka/issues/426

**Comment by slinkydeveloper** [comment]
@aliok I can help with second and third issue, not much I can do for the first one

**Comment by matzew** [comment]
with https://github.com/knative-sandbox/eventing-kafka/pull/550 merged, this is done

/close
