### ISSUE TITLE
[KafkaChannels] Topic Configuration Inconsistencies

### ISSUE THREAD

**Issue by travis-minke-sap** [knative-sandbox/eventing-kafka#817]
**Describe the bug**
This issue is a combination of a bug and a feature request, all pertaining to the same area of the code, which will require a refactor to align the behavior on a consistent approach.

First the bug...

The ConfigMap, shared by the two KafkaChannel implementations, includes a section **eventing-kafka -> kafka -> topic** which contains "default" values used when creating Kafka topics (NumPartitions, ReplicationFactor, RetentionMillis). These values are ONLY "defaults" to be used IF the KafkaChannel CR did not include them in the Spec.  The bug is that the default **NumPartitions** and **ReplicationFactor** are NEVER used, because the defaulting WebHook implementation will instead set KafkaChannel CR instances using hardcoded constants.  So, by the time the defaults from the ConfigMap are to be used, the KafkaChannel CR always has values and doesn't need the ConfigMap settings.

Next the feature...

The reason the **RetentionMillis** default in the ConfigMap (as described above) IS used, is because that value is NOT exposed in the KafkaChannel Spec with the other two fields.  There is no good reason for this omission other than the rich history of merging the two KafkaChannel implementations together ; ).  Excluding this config value from the KafkaChannel Spec prevents users from creating Topics with different retention periods.  We should expose the Kafka Topic Retention time in the KafkaChannel Spec with the other two fields, and handle them all in a consistent manner.  A PR (#722) was previously created to do this, but had some shortcomings.  It would be good to create a more comprehensive solution that addressed the general handling of these Topic configurations.

 **Expected behavior**
The proposed solution for aligning the handling of Topic configuration is to...
- Remove the **eventing-kafka -> kafka -> topic** section from the ConfigMap
- Add the **RetentionDuration** (as an ISO-8601 Duration String) to the KafkaChannel Spec
- Add Validation and Parsing of the new **RetentionDuration** ISO-8601 value.
- Add the **RetentionDuration** to the Defaulting WebHook to set default values to the 7 day period previously used in the base ConfigMap default.
- Remove the no-op logic of checking the ConfigMap if values in KafkaChannel are not set (since the Defaulting WebHook guarantees they will be set)
- Create a Post-Install job that will populate existing KafkaChannel instances with the **RetentionDuration** value matching their current configuration state.

 **To Reproduce**
- Create a KafkaChannel without any Spec and notice that the defaults in the ConfigMap are not used.
- Also, notice that the KafkaChannel Spec does not include the Retention value.

 **Knative release version**
All releases - /main as of this PR.

 **Additional context**
The plan is to add the new **RetentionDuration** field to the KafkaChannel Spec, while keeping the KafkaChannel version on **v1beta1**.  The handling of existing KafkaChannels (who have not specified this value) will operate as follows...

- Existing KafkaChannels (prior to upgrading eventing-kakfa) will have already been reconciled, with the corresponding Kafka Topic having been created using the ConfigMap default.  Future re-reconciliations of the KafkaChannel do NOT re-create the Kafka Topic and so it's configuration will not be modified.
- If a manual edit is made to the KafkaChannel (adding a label for instance), then the Defaulting WebHook will update the Spec with the default value.  If the user had previously changed the default/base **RetentionMillis** value in the ConfigMap, then these two values will not match, and the KafkaChannel CR Spec will not accurately reflect the true value configured in Kafka for that Topic.  The actual Kafka Topic will not be modified however, and will continue to operate as it had before.  The new default value would only ever take effect if the Topic was somehow torn-down and the KafkaChannel re-reconciled, which is not a supported production use case.  
- If desired, users can protect themselves from the above situation, by running the **config/channel/post-install** job to bring all existing KafkaChannels into alignment with the current Kafka Topic configuration.

**Tasks**
- [X] Add RetentionDuration to KafkaChannel CRD and remove Topic configuration from ConfigMap. (PR #828)
- [X] Close PR #722
- [X] Implement post-install job to populate RetentionDuration of existing KafkaChannels from current Topic configuration. (PR #834)
- [X] Close Issue #813 as no longer relevant.
- [X] Create a follow-up Issue to remove the post-install job once v0.26.0 has been built. (Issue #846)

**Comment by travis-minke-sap** [comment]
Closing Issue as all sub-tasks have been completed/merged.
